pipeline {
  agent any
  environment {
    IMAGE_NAME = "<DOCKERHUB_USER>/laravel-cicd-app"
    IMAGE_TAG = "${env.BUILD_NUMBER}-${env.GIT_COMMIT.substring(0,7)}"
  }
  stages {
    stage('Checkout') { steps { checkout scm } }
    stage('Build Image') { steps { sh 'docker build -t ${IMAGE_NAME}:${IMAGE_TAG} -f docker/php-fpm.Dockerfile .' } }
    stage('Push Image') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
          sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
          sh 'docker push ${IMAGE_NAME}:${IMAGE_TAG}'
        }
      }
    }
    stage('Deploy to Kubernetes') { steps { sh 'kubectl set image deployment/laravel-app laravel-app=${IMAGE_NAME}:${IMAGE_TAG} -n laravel' } }
  }
}
